#!/usr/bin/env bash
# Generate every icon size from the master SVGs.
#
#   ./Scripts/make_icons.sh
#
# Input (vector, generated by gen_icon_svg.py — or edit by hand):
#   Assets/icon/AppIcon.svg   full-bleed colour icon (rounded-rect app icon look)
#
# Outputs:
#   Assets/icon/AppIcon.iconset/*.png   the 10 macOS-named sizes
#   Assets/icon/AppIcon.icns            packed icns (bundled by package_app.sh)
#   Assets/icon/png/icon_<n>.png        colour PNGs 16..1024 (popover / settings / README)
#
# The menu-bar glyph is drawn live by the app (ClawdGlyph.swift), not rasterized here.
#
# Needs: rsvg-convert (brew install librsvg), iconutil, sips (system).
set -euo pipefail
cd "$(dirname "$0")/.."

ICON_DIR="Assets/icon"
APP_SVG="$ICON_DIR/AppIcon.svg"

command -v rsvg-convert >/dev/null || { echo "✗ rsvg-convert not found (brew install librsvg)" >&2; exit 1; }
[ -f "$APP_SVG" ] || { echo "✗ missing $APP_SVG" >&2; exit 1; }

render() { # svg w h out
  rsvg-convert -w "$2" -h "$3" -a "$1" -o "$4"
}

echo "▸ AppIcon.iconset…"
ISET="$ICON_DIR/AppIcon.iconset"
rm -rf "$ISET"; mkdir -p "$ISET"
# name:size pairs required by iconutil
for pair in \
  "icon_16x16:16"      "icon_16x16@2x:32" \
  "icon_32x32:32"      "icon_32x32@2x:64" \
  "icon_128x128:128"   "icon_128x128@2x:256" \
  "icon_256x256:256"   "icon_256x256@2x:512" \
  "icon_512x512:512"   "icon_512x512@2x:1024"; do
  name="${pair%%:*}"; size="${pair##*:}"
  render "$APP_SVG" "$size" "$size" "$ISET/$name.png"
done

echo "▸ AppIcon.icns…"
iconutil -c icns "$ISET" -o "$ICON_DIR/AppIcon.icns"

echo "▸ colour PNGs…"
PNG_DIR="$ICON_DIR/png"
rm -rf "$PNG_DIR"; mkdir -p "$PNG_DIR"
for n in 16 32 64 128 256 512 1024; do
  render "$APP_SVG" "$n" "$n" "$PNG_DIR/icon_$n.png"
done

echo "✓ done → $ICON_DIR"
ls -1 "$ICON_DIR"/AppIcon.icns "$PNG_DIR"/*.png 2>/dev/null | sed 's/^/    /'
